export {default as Dashboard } from "./Dashboard"
export {default as ECommerce } from "./ECommerce"
export {default as Inbox } from "./Inbox"
export {default as Kanban } from "./Kanban"
export {default as Products } from "./Products"
export {default as SignIn } from "./SignIn"
export {default as SignUp } from "./SignUp"
export {default as User } from "./User"
