"use client"

import Head from 'next/head'
import { RiMoonFill } from "react-icons/ri";
import { ImSun } from "react-icons/im";
import { ThemeProvider, useTheme } from 'next-themes';
import OffCanvasSidebar from '@/components/OffCanvasSidevbar';

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Dark/Light Mode Switcher with Sidebar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body>
        <header>
          <OffCanvasSidebar />
        </header>
        <main className='h-screen flex flex-col justify-center items-center'>
          <h1 className="text-7xl font-bold">{theme === "dark" ? "Dark" : "Light"}{" "}<span className='text-purple-600'>Mode</span></h1>
          <p className='text-purple-600 font-semibold py-6'>Click the button to swicth between Modes</p>
          {theme === "light" ?
            <div onClick={() => setTheme("dark")} className='border-2 border-[#9898ba] cursor-pointer w-24 py-2 px-4 flex justify-center mx-auto rounded-lg'>
              <RiMoonFill size={60} style={{ fill: "#3636c1" }} />
            </div> :
            <div onClick={() => setTheme("light")} className='border-2 border-[#9898ba] cursor-pointer w-24 py-2 px-4 flex justify-center mx-auto rounded-lg'>
              <ImSun size={60} style={{ fill: "#3636c1" }} />
            </div>
          }
        </main>
      </body>
    </>
  )
}
